project:
  type: website

website:
  title: "Solow Growth Analysis"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Freedom"
        file: Heritage-Index.qmd
      - text: "Business"
        file: Business-Ready.qmd
      - text: "Corruption"
        file: Corruption-Index.qmd
      - text: "Solow"
        file: Solow-Models.qmd

format:
  html:
    theme: cosmo
    
execute:
  warning: false
  message: false
  echo: false
  include: true